---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: vmware/dispatch-golang-ci
    tag: "1.10"

inputs:
- name: dispatch
  path: src/github.com/vmware/dispatch

- name: release-context
  optional: true

outputs:
- name: dispatch-binaries

run:
  path: /bin/bash
  args:
  - -c
  - |
    set -e -u -x

    export GOPATH=$PWD
    if [[ -e release-context/tag ]]; then
      export VERSION=$(cat release-context/tag)
    fi
    cd $GOPATH/src/github.com/vmware/dispatch
    make binaries
    mv bin/* $GOPATH/dispatch-binaries/