// Code generated by mockery v1.0.0
package mocks

import client "github.com/vmware/dispatch/pkg/client"
import context "context"

import mock "github.com/stretchr/testify/mock"

// ImageGetter is an autogenerated mock type for the ImageGetter type
type ImageGetter struct {
	mock.Mock
}

// GetImage provides a mock function with given fields: ctx, imageName
func (_m *ImageGetter) GetImage(ctx context.Context, imageName string) (*client.Image, error) {
	ret := _m.Called(ctx, imageName)

	var r0 *client.Image
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.Image); ok {
		r0 = rf(ctx, imageName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Image)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, imageName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
